apiVersion: v1
kind: Service
metadata:
  labels:
    name: frontend
  name: frontend-svc
spec:
  selector:
    name: frontend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer